# Generated by Django 5.2.8 on 2025-12-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubFoot', '0010_alter_doc_doc_choisie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='doc_choisie',
            field=models.CharField(choices=[('cours-sql-sh-.pdf', 'cours-sql-sh-.pdf'), ('DevMeetup-Eel-20190122.pdf', 'DevMeetup-Eel-20190122.pdf'), ('pyinstaller-org-en-v3.3.pdf', 'pyinstaller-org-en-v3.3.pdf'), ('pyinstaller.pdf', 'pyinstaller.pdf')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='img',
            name='image_choisie',
            field=models.CharField(choices=[('backFoot2.jpg', 'backFoot2.jpg'), ('BelgiumClub_2025.jpg', 'BelgiumClub_2025.jpg'), ('caption.jpg', 'caption.jpg'), ('cLUB mONS.png', 'cLUB mONS.png'), ('club.jpg', 'club.jpg'), ('cLUBmONS.jpg', 'cLUBmONS.jpg'), ('cLUBmONS.png', 'cLUBmONS.png'), ('cLUB_mONS.png', 'cLUB_mONS.png'), ('g1.jpg', 'g1.jpg'), ('g2.jpg', 'g2.jpg'), ('header.jpg', 'header.jpg'), ('header10.jpg', 'header10.jpg'), ('header11.jpg', 'header11.jpg'), ('header12.jpeg', 'header12.jpeg'), ('header12.jpg', 'header12.jpg'), ('header13.jpeg', 'header13.jpeg'), ('header14.jpeg', 'header14.jpeg'), ('header15.jpeg', 'header15.jpeg'), ('header16.jpeg', 'header16.jpeg'), ('header17.jpeg', 'header17.jpeg'), ('header18.jpg', 'header18.jpg'), ('header19.jpeg', 'header19.jpeg'), ('header19.jpg', 'header19.jpg'), ('header2.jpg', 'header2.jpg'), ('header3.jpg', 'header3.jpg'), ('header33.jpg', 'header33.jpg'), ('header4.jpg', 'header4.jpg'), ('header5.jpg', 'header5.jpg'), ('header6.jpg', 'header6.jpg'), ('header7.jpg', 'header7.jpg'), ('header8.jpg', 'header8.jpg'), ('header9.jpg', 'header9.jpg'), ("Images en forme de dessins animés pour le fichier SVG d'un match de footbal_20250831_184313_0000.jpg", "Images en forme de dessins animés pour le fichier SVG d'un match de footbal_20250831_184313_0000.jpg"), ('images.jpg', 'images.jpg'), ('IMG-14-09-2025-WA0000.jpg', 'IMG-14-09-2025-WA0000.jpg'), ('imgVeteran1.jpg', 'imgVeteran1.jpg'), ('LOGO.jpg', 'LOGO.jpg'), ('logo01.png', 'logo01.png'), ('Mons.jpg', 'Mons.jpg'), ('Mons.png', 'Mons.png'), ('mons1a.jpg', 'mons1a.jpg'), ('mons1a.png', 'mons1a.png'), ('mons1a_001.jpg', 'mons1a_001.jpg'), ('mons1a_002.jpg', 'mons1a_002.jpg'), ('mons1a_003.jpg', 'mons1a_003.jpg'), ('mons1a_004.jpg', 'mons1a_004.jpg'), ('mons1b.jpg', 'mons1b.jpg'), ('mons1c.jpg', 'mons1c.jpg'), ('mons1d.jpg', 'mons1d.jpg'), ('player.jpg', 'player.jpg'), ('playeR.png', 'playeR.png'), ('Sans titre.png', 'Sans titre.png')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vid',
            name='video_choisie',
            field=models.CharField(choices=[('static_Vid.mp4', 'static_Vid.mp4'), ('static_Vid01.mp4', 'static_Vid01.mp4'), ('static_Vid02.mp4', 'static_Vid02.mp4'), ('VID-14-09-2025-01.mp4', 'VID-14-09-2025-01.mp4')], default='', max_length=200),
        ),
    ]
